# ---------------------------------------------------------------------------- #
# Installation
# ---------------------------------------------------------------------------- #


# package/app managers
brew install cask
brew install mas
brew install getantibody/tap/antibody

# developing tools
brew install git
brew install pyenv
brew install micro

# cli enhancers
brew install bat
brew install diff-so-fancy
brew install fzf
brew install htop
brew install ncdu
brew install prettyping
brew install tldr
brew install fd


# ---------------------------------------------------------------------------- #
# Antibody installs (Zsh plugins)
# ---------------------------------------------------------------------------- #


bundles="
mafredri/zsh-async
zsh-users/zsh-completions
sindresorhus/pure
zsh-users/zsh-syntax-highlighting
"

file_header='# These plugin-sourcing commands has been generated by antibody.
# Check the dotfiles'"'"' install.sh to know more about installed plugins.\n\n'
plugin_sources="$(antibody bundle $bundles)"
echo "${file_header}${plugin_sources}" >! "$ZDOTDIR/plugins.zsh"
antibody update

unset bundles
unset file_header
unset newline
unset plugin_sources


# ---------------------------------------------------------------------------- #
# Symlinking
# ---------------------------------------------------------------------------- #


mydir=${0:a:h}

# symlink files starting with dot if they exist
for file in $mydir/.^DS_Store; do
	filename="$(basename $file)"
	ln -s $file $HOME/$filename
done
# symlink files not starting with dot if they exist
for file in $mydir/^install.sh; do
	filename="$(basename $file)"
	ln -s $file $HOME/$filename
done

unset mydir
unset file
unset filename
