#! /bin/sh


set -e


cd "$(dirname "$0")"
DOTFILES=$(pwd -P)


#
# Interactors
#


info() {
    printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

success() {
    printf "\r  \033[2K[ \033[00;32mOK\033[0m ] $1\n"
}

fail() {
    printf "\r  \033[2K[\033[0;31mFAIL\033[0m] $1\n"
    exit 1
}


#
# Utilities
#


link_file() {
    if [ -e "$2" ]; then
        if [ "$(readlink "$2")" = "$1" ]; then
            success "skipped $1"
            return 0
        else
            [ "$DRY_RUN" = 0 ] && mv "$2" "$2.backup"
            success "moved $2 to $2.backup"
        fi
    fi
    [ "$DRY_RUN" = 0 ] && ln -sf "$1" "$2"
    success "linked $1 to $2"
}


#
# Arguments
#


DRY_RUN=0

parse_arguments() {
    if [ "$1" = "" ]; then
        return 0
    elif [ "$1" != "--dry-run" ] || [ "$2" != "" ]; then
        echo "$0: illigal option(s) '$@'" >&2
        echo "usage: $0 [--dry-run]" >&2
        exit 1
    fi
    DRY_RUN=1
}


#
# Bootstrappers
#


setup_dotfiles() {
    info "setupping dotfiles"
    for src in $DOTFILES/.*; do
        src_name="$(basename "$src")"
        [ "$src_name" = ".DS_Store" ] && continue
        [ "$src_name" = "." ] && continue
        [ "$src_name" = ".." ] && continue
        [ "$src_name" = ".git" ] && continue
        dst="$HOME/$src_name"
        link_file "$src" "$dst"
    done
}

setup_antibody() {
    info "setupping antibody"
    file_header='# Plugin-sourcing commands generated by Antibody.\n\n'
    plugin_sources="$(antibody bundle <"$DOTFILES/Pluginfile")"
    [ "$DRY_RUN" = 0 ] && echo "${file_header}${plugin_sources}" >| "$ZDOTDIR/plugins.zsh"
    success "generated $ZDOTDIR/plugins.zsh"
    [ "$DRY_RUN" = 0 ] && antibody update
    success "updated antibody"
}

setup_programs() {
    info "setupping programs"
    [ "$DRY_RUN" = 0 ] && $(brew --prefix)/opt/fzf/install --bin
    success "installed fzf"
    [ "$DRY_RUN" = 0 ] && chmod u+s $(which htop)
    [ "$DRY_RUN" = 0 ] && sudo chown root:wheel $(which htop)
    success "installed htop"
}


#
# Main
#


parse_arguments "$@"
setup_dotfiles
source $HOME/.zshenv
setup_antibody
setup_programs
echo "All installed!"
