tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "antibody"
brew "coreutils"
brew "diff-so-fancy"
brew "fd"
brew "fzf"
brew "htop"
brew "mas"
brew "node"
brew "pyenv"
brew "pyenv-virtualenv"
brew "tealdeer"
brew "wget"
brew "yarn"

cask "alfred"
cask "appcleaner"
cask "discord"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "mactex-no-gui"
cask "skim"
cask "spectacle"
cask "spotify"
cask "sublime-text"
cask "transmission"
cask "vlc"

mas "Amphetamine", id: 937984704
mas "Telegram", id: 747648890
mas "Things", id: 904280696
