# Copyright (c) 2019 Kirill Gashkov
#
# Distributed under MIT License. See LICENSE file for details.

import os
import sys
import subprocess


def main():
    setup_dir = sys.argv[1]

    print '--- setup.py started ---'
    setup_antibody(setup_dir)
    setup_fzf()
    setup_htop()
    print '--- setup.py finished ---'


def setup_antibody(setup_dir):
    with open(os.path.join(setup_dir, 'Pluginfile'), 'r') as f:
        pluginfile_contents = f.read()

    p = subprocess.Popen(
        ['antibody', 'bundle'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    plugin_sources = p.communicate(input=pluginfile_contents)[0].decode()

    plugins_content_lines = [
        '# Plugin-sourcing commands generated by Antibody.',
        '\n\n',
        plugin_sources,
    ]

    with open(os.path.expanduser('~/.zsh/plugins.zsh'), 'w+') as f:
        f.writelines(plugins_content_lines)

    subprocess.check_call(['antibody', 'update'])


def setup_fzf():
    os.system('$(brew --prefix)/opt/fzf/install --bin')


def setup_htop():
    os.system('chmod u+s $(which htop)')
    os.system('sudo chown root:wheel $(which htop)')


if __name__ == '__main__':
    main()
