#! /bin/zsh

# ---------------------------------------------------------------------------- #
# Zsh installation
# ---------------------------------------------------------------------------- #


# change default shell to Zsh installed by Homebrew
sudo -s 'echo /usr/local/bin/zsh >> /etc/shells' && chsh -s /usr/local/bin/zsh
# get clifiles' directory using Zsh
clifiles_dir=${0:A:h}
# symlink files starting with dot to home
for file in $clifiles_dir/.*; do
	filename="$(basename $file)"
	[[ "$filename" == "DS_Store" ]] && continue
	ln -s $file $HOME/$filename
done
# initialize Zsh session
source $HOME/.zshenv
source $ZDOTDIR/.zshrc


# ---------------------------------------------------------------------------- #
# Plugins
# ---------------------------------------------------------------------------- #


# install Antibody plugins
file_header='# Plugin-sourcing commands generated by Antibody.\n\n'
plugin_sources="$(antibody bundle <"$clifiles_dir/Pluginfile")"
echo "${file_header}${plugin_sources}" >! "$ZDOTDIR/plugins.zsh"
antibody update

# install fzf
$(brew --prefix)/opt/fzf/install --bin

# install htop
chmod u+s $(which htop)
sudo chown root:wheel $(which htop)


# ---------------------------------------------------------------------------- #
# Cleanup
# ---------------------------------------------------------------------------- #


unset clifiles_dir
unset file
unset filename
unset file_header
unset plugin_sources
