#!/bin/sh
#
# Executes the specified quickstart file in the current working directory or
# in the optionally specified working directory.

fatal() {
    echo "$(basename "$0"): $1" >&2
    exit 1
}

warning() {
    echo "$1" >&2
}

confirm() {
    printf '%s' "$1" >&2
    read -r answer

    case "$answer" in
        [Yy]*) return 0;;
    esac

    return 1
}


if [ "$#" -eq 0 ]; then
    warning "usage: $(basename "$0") <quickstart-file> [<working-directory>]"
    exit 1
fi


library="${XDG_CONFIG_HOME:-$HOME/.config}/quickstart/library"


if [ -z "$1" ]; then
    fatal "quickstart file was not specified"
fi

if [ ! -e "$library/$1" ]; then
    fatal "quickstart file '$1' does not exist in the library"
fi

if [ ! -x "$library/$1" ]; then
    fatal "quickstart file '$1' is not executable"
fi

[ -n "$2" ] && did_cd=0 && mkdir -p "$2" && cd "$2" && did_cd=1

if [ "$did_cd" = 0 ]; then
    fatal "specified working directory '$2' cannot be reached"
fi

if [ -n "$(ls -A "$PWD")" ]; then
    warning "Working directory '$PWD' is not empty."
    confirm "Do you want to continue? [Y/n] " || { warning "Abort."; exit 2; }
fi


"$library/$1"
