window:
  decorations: none
  opacity: 0.9

font:
  normal:
    family: JetBrains Mono
  size: 13.0
  offset:
    y: 10
  glyph_offset:
    y: 5

shell:
  program: /usr/local/bin/tmux
  args:
    - start-server
    - ;
    - run-shell
    - /usr/local/bin/tmux has-session || /usr/local/bin/tmux new-session -d -s unnamed
    - ;
    - attach-session

key_bindings: []
