import = ["~/Repositories/@kirillgashkov/dotfiles/dotfiles/config/alacritty/tokyonight/tokyonight_night.toml"]

[window]
padding.x = 10
padding.y = 10
dynamic_padding = true
decorations = "buttonless"
opacity = 0.9

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 13.0
offset.y = 10
glyph_offset.y = 5

[colors]
transparent_background_colors = true

[shell]
program = "/usr/local/bin/tmux"
args = [
    "start-server",
    ";",
    "run-shell",
    "/usr/local/bin/tmux has-session || /usr/local/bin/tmux new-session -d -s \"-\"",
    ";",
    "attach-session"
]

[keyboard]
bindings = [
    { key = "N", mods = "Command",       chars = "\u0002\u0063"             },  # New window              (C-b c)
    { key = "N", mods = "Command|Shift", chars = "\u0002\u001b\u0043"       },  # New session             (C-b M-C) (User-defined)
    { key = "D", mods = "Command",       chars = "\u0002\u0025"             },  # Split pane vertically   (C-b %)
    { key = "D", mods = "Command|Shift", chars = "\u0002\u0022"             },  # Split pane horizontally (C-b ")
    { key = "R", mods = "Command",       chars = "\u0002\u001b\u0052"       },  # Restart pane            (C-b M-R) (User-defined)
    { key = "W", mods = "Command",       chars = "\u0002\u0078"             },  # Close pane              (C-b x)
    { key = "W", mods = "Command|Shift", chars = "\u0002\u001b\u0058"       },  # Close session           (C-b M-X) (User-defined)

    { key = "K", mods = "Command|Shift", chars = "\u0002\u001b\u004b"       },  # Clear scrollback buffer (C-b M-K) (User-defined)
    { key = "Y", mods = "Command",       chars = "\u0002\u001b\u007b"       },  # Toggle copy mode        (C-b M-{) (User-defined)
    { key = "Z", mods = "Command",       chars = "\u0002\u007a"             },  # Toggle zoom             (C-b z)

    { key = "H", mods = "Command",       chars = "\u0002\u001b\u005b\u0044" },  # Focus left pane         (C-b Left)
    { key = "L", mods = "Command",       chars = "\u0002\u001b\u005b\u0043" },  # Focus right pane        (C-b Right)
    { key = "K", mods = "Command",       chars = "\u0002\u001b\u005b\u0041" },  # Focus top pane          (C-b Up)
    { key = "J", mods = "Command",       chars = "\u0002\u001b\u005b\u0042" },  # Focus bottom pane       (C-b Down)

    { key = "!", mods = "Command",       chars = "\u0002\u0031"             },  # Focus window 1          (C-b 1)
    { key = "@", mods = "Command",       chars = "\u0002\u0032"             },  # Focus window 2          (C-b 2)
    { key = "#", mods = "Command",       chars = "\u0002\u0033"             },  # Focus window 3          (C-b 3)
    { key = ";", mods = "Command",       chars = "\u0002\u0034"             },  # Focus window 4          (C-b 4)
    { key = "%", mods = "Command",       chars = "\u0002\u0035"             },  # Focus window 5          (C-b 5)
    { key = ":", mods = "Command",       chars = "\u0002\u0036"             },  # Focus window 6          (C-b 6)
    { key = "?", mods = "Command",       chars = "\u0002\u0037"             },  # Focus window 7          (C-b 7)
    { key = "*", mods = "Command",       chars = "\u0002\u0038"             },  # Focus window 8          (C-b 8)
    { key = "(", mods = "Command",       chars = "\u0002\u001b\u0028"       },  # Focus last window       (C-b M-() (User-defined)

    { key = "P", mods = "Command",       chars = "\u0002\u001b\u0053"       },  # Go to session           (C-b M-S) (User-defined)
    { key = "P", mods = "Command|Shift", chars = "\u0002\u001b\u0050"       },  # Command palette         (C-b M-P) (User-defined)

    { key = "Y", mods = "Control|Alt", chars = "\u001b\u0019"               },  # Emit raw key            (M-C-y)
    { key = "N", mods = "Control|Alt", chars = "\u001b\u000e"               },  # Emit raw key            (M-C-n)
    { key = "P", mods = "Control|Alt", chars = "\u001b\u0010"               },  # Emit raw key            (M-C-p)
    { key = "E", mods = "Control|Alt", chars = "\u001b\u0005"               },  # Emit raw key            (M-C-e)
    { key = "Space", mods = "Control|Alt", chars = "\u001b[32;7u"           }   # Emit raw key            (M-C-Space)
]
