window:
  padding:
    x: 10
    y: 10
  dynamic_padding: true
  decorations: buttonless

font:
  normal:
    family: JetBrains Mono
  size: 13.0
  offset:
    y: 10
  glyph_offset:
    y: 5

import:
  # - ~/.config/alacritty/themes/atom-one-light.yml
  - ~/.config/alacritty/themes/tomorrow-night.yml

shell:
  program: /usr/local/bin/tmux
  args:
    - start-server
    - ;
    - run-shell
    - "/usr/local/bin/tmux has-session || /usr/local/bin/tmux new-session -d -s unnamed"
    - ;
    - attach-session

key_bindings:
  - { key: Q,     mods: Command|Alt,    chars: "\x02\x1b\x51"     }  # Kill server              (C-b M-Q) (User-defined)

  - { key: N,     mods: Command,        chars: "\x02\x63"         }  # New window               (C-b c)
  - { key: N,     mods: Command|Shift,  chars: "\x02\x1b\x43"     }  # New session              (C-b M-C) (User-defined)
  - { key: W,     mods: Command,        chars: "\x02\x78"         }  # Close pane               (C-b x)
  - { key: W,     mods: Command|Shift,  chars: "\x02\x1b\x58"     }  # Close session            (C-b M-X) (User-defined)

  - { key: D,     mods: Command,        chars: "\x02\x25"         }  # Split pane vertically    (C-b %)
  - { key: D,     mods: Command|Shift,  chars: "\x02\x22"         }  # Split pane horizontally  (C-b ")

  - { key: Key1,  mods: Command,        chars: "\x02\x31"         }  # Select window 1          (C-b 1)
  - { key: Key2,  mods: Command,        chars: "\x02\x32"         }  # Select window 2          (C-b 2)
  - { key: Key3,  mods: Command,        chars: "\x02\x33"         }  # Select window 3          (C-b 3)
  - { key: Key4,  mods: Command,        chars: "\x02\x34"         }  # Select window 4          (C-b 4)
  - { key: Key5,  mods: Command,        chars: "\x02\x35"         }  # Select window 5          (C-b 5)
  - { key: Key6,  mods: Command,        chars: "\x02\x36"         }  # Select window 6          (C-b 6)
  - { key: Key7,  mods: Command,        chars: "\x02\x37"         }  # Select window 7          (C-b 7)
  - { key: Key8,  mods: Command,        chars: "\x02\x38"         }  # Select window 8          (C-b 8)
  - { key: Key9,  mods: Command,        chars: "\x02\x39"         }  # Select window 9          (C-b 9)

  - { key: Left,  mods: Command,        chars: "\x02\x1b\x5b\x44" }  # Select left pane         (C-b Left)
  - { key: Right, mods: Command,        chars: "\x02\x1b\x5b\x43" }  # Select right pane        (C-b Right)
  - { key: Up,    mods: Command,        chars: "\x02\x1b\x5b\x41" }  # Select top pane          (C-b Up)
  - { key: Down,  mods: Command,        chars: "\x02\x1b\x5b\x42" }  # Select bottom pane       (C-b Down)

  - { key: Left,  mods: Command|Shift,  chars: "\x02\x70"         }  # Select left window       (C-b p)
  - { key: Right, mods: Command|Shift,  chars: "\x02\x6e"         }  # Select right window      (C-b n)

  - { key: S,     mods: Command|Shift,  chars: "\x02\x1b\x53"     }  # Select session           (C-b M-S) (User-defined)

  - { key: R,     mods: Command,        chars: "\x02\x2c"         }  # Rename window            (C-b ,)
  - { key: R,     mods: Command|Shift,  chars: "\x02\x24"         }  # Rename session           (C-b $)

  - { key: K,     mods: Command,        chars: "\x02\x1b\x4b"     }  # Clear scrollback buffer  (C-b M-K) (User-defined)
