window:
  decorations: none
  opacity: 0.9

font:
  normal:
    family: JetBrains Mono
  size: 13.0
  offset:
    y: 10
  glyph_offset:
    y: 5

shell:
  program: /usr/local/bin/tmux
  args:
    - start-server
    - ;
    - run-shell
    - /usr/local/bin/tmux has-session || /usr/local/bin/tmux new-session -d -s unnamed
    - ;
    - attach-session

key_bindings:
  - { key: N,     mods: Command,        chars: "\x02\x63"         }  # New window               (C-b c)
  - { key: N,     mods: Command|Shift,  chars: "\x02\x1b\x43"     }  # New session              (C-b M-C) (User-defined)
  - { key: D,     mods: Command,        chars: "\x02\x25"         }  # Split pane vertically    (C-b %)
  - { key: D,     mods: Command|Shift,  chars: "\x02\x22"         }  # Split pane horizontally  (C-b ")
  - { key: W,     mods: Command,        chars: "\x02\x78"         }  # Close pane               (C-b x)
  - { key: W,     mods: Command|Shift,  chars: "\x02\x1b\x58"     }  # Close session            (C-b M-X) (User-defined)
