# ---------------------------------------------------------------------------- #
# Init
# ---------------------------------------------------------------------------- #


# get dotfiles' root assuming this file located where it should be
dotfiles_dir=${0:A:h:h}


# ---------------------------------------------------------------------------- #
# Installations
# ---------------------------------------------------------------------------- #


# Homebrew & Brewfile
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew bundle --file "$dotfiles_dir/installer/Brewfile"

# Dotfiles
for file in $dotfiles_dir/dotfiles/.*; do
	filename="$(basename $file)"
	[[ "$filename" == "DS_Store" ]] && continue
	ln -s $file $HOME/$filename
done

# Zsh & Antibody
source $HOME/.zshenv
source $ZDOTDIR/.zshrc
file_header='# Plugin-sourcing commands generated by Antibody.\n\n'
plugin_sources="$(antibody bundle <"$dotfiles_dir/installer/Antibody")"
echo "${file_header}${plugin_sources}" >! "$ZDOTDIR/plugins.zsh"
antibody update


# ---------------------------------------------------------------------------- #
# Deinit
# ---------------------------------------------------------------------------- #


# unset temporary variables
unset dotfiles_dir
unset file
unset file_header
unset plugin_sources
